loadModule("NLF", TRUE)
loadModule("NNO", TRUE)
loadModule("SOC", TRUE)
loadModule("PSD", TRUE)
loadModule("CTL", TRUE)

evalqOnLoad({
    ## show methods
    setMethod("show", "Rcpp_NLFV", function(object){
        cat("Object of reference-class: NLFV\n")
        cat(paste("Dimension:", object$dims,"\n"))
        cat("\n")
        cat("Showing head of NLF-variable\n")
        print(head(object$u))
    })
    setMethod("show", "Rcpp_NNOV", function(object){
        cat("Object of reference-class: NNOV\n")
        cat(paste("Dimension:", object$dims,"\n"))
        cat("\n")
        cat("Showing head of NNO-variable\n")
        print(head(object$u))
    })
    setMethod("show", "Rcpp_SOCV", function(object){
        cat("Object of reference-class: SOCV\n")
        cat(paste("Dimension:", object$dims,"\n"))
        cat("\n")
        cat("Showing head of SOC-variable\n")
        print(head(object$u))
    })
    setMethod("show", "Rcpp_PSDV", function(object){
        cat("Object of reference-class: PSDV\n")
        cat(paste("Dimension:", object$dims,"\n"))
        cat("\n")
        cat("Showing head of PSD-variable\n")
        print(head(object$u))
    })
    setMethod("show", "Rcpp_CTRL", function(object){
        cat("Control parameters used in optimization:\n\n")
        cat(paste("Maximum iterations:\t", object$maxiters,"\n"))
        cat(paste("Absolute tolerance:\t", object$abstol,"\n"))
        cat(paste("Relative tolerance:\t", object$reltol,"\n"))
        cat(paste("Feasible tolerance:\t", object$feastol,"\n"))
        cat(paste("Tracing progress:\t", object$trace,"\n"))
    })
})
